name: Build cpac_templates Docker image

on:
  push:

jobs:
  Ubuntu:
    name: Build Docker image for C-PAC
    strategy:
      matrix:
        Dockerfile: 
        - Ubuntu.bionic-non-free
    runs-on: ubuntu-latest
    steps:
      - name: Check out C-PAC_templates
        uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 2
          lfs: true
      - run: git lfs pull
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set image tag
        run: |
          echo DOCKER_NAME=$(echo "ghcr.io/${{ github.repository }}" | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}},priority=900
            type=semver,pattern={{major}}.{{minor}}.{{patch}},priorty=899
            type=semver,pattern={{major}}.{{minor}},priority=898
            type=semver,pattern={{major}},priority=897
            type=ref,event=branch,priority=800
            type=ref,event=pr,priority=799
            type=raw,value=latest,enable={{is_default_branch}},priorty=700
            type=sha,priority=600,onlatest=false
      - name: Build and push Docker image
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          file: .github/Dockerfiles/cpac_templates.Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
