name: Build cpac_templates Docker image

on:
  push:

jobs:
  Ubuntu:
    name: Build Docker image for C-PAC
    strategy:
      matrix:
        Dockerfile: 
        - Ubuntu.bionic-non-free
    runs-on: ubuntu-latest
    steps:
      - name: Check out C-PAC_templates
        uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 2
          lfs: true
      - run: git lfs pull
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set image tag
        run: |
          echo DOCKER_NAME=$(echo "ghcr.io/${{ github.repository }}" | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
          echo DOCKER_TAG=$(echo "latest") >> $GITHUB_ENV
      - name: Append branch to image tag
        if: github.ref_type == 'branch' && github.ref_name != 'main'
        run: |
          GITHUB_BRANCH=${{ github.ref_name }}
          echo DOCKER_TAG=`echo "${{ env.DOCKER_TAG }}_${GITHUB_BRANCH//\//_}"` >> $GITHUB_ENV
      - name: Build and push Docker image
        if: github.ref_type == 'branch'
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          file: .github/Dockerfiles/cpac_templates.Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_NAME }}:${{ env.DOCKER_TAG }}
      - name: Docker meta
        id: meta
        if: github.ref_type == 'tag'
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}.{{patch}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      - name: Build and push Docker image
        if: github.ref_type == 'tag'
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          file: .github/Dockerfiles/cpac_templates.Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
